replicaCount: 1

image:
  registry: quay.io
  repository: icdh/core-dump-handler
  tag: main
  pullPolicy: Always
  request_mem: "64Mi"
  request_cpu: "250m"
  limit_mem: "128Mi"
  limit_cpu: "500m"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Size of the Persistent volume to create
hostStorage: 1Gi
coreStorage: 10Gi
storageClass: hostclass

composer:
  ignoreCrio: false
  crioImageCmd: "img"
  logLevel: "Warn"
  # Double curlies are required otherwise helm trys to parse the string
  filenameTemplate: "{{uuid}}-dump-{{timestamp}}-{{hostname}}-{{exe_name}}-{{pid}}-{{signal}}"
  logLength: 500
  podSelectorLabel: ""

daemonset:
  name: "core-dump-handler"
  label: "core-dump-ds"
  hostDirectory: "/var/mnt/core-dump-handler"
  coreDirectory: "/var/mnt/core-dump-handler/cores"
  crioEndpoint: "unix:///run/containerd/containerd.sock"
  suidDumpable: 2
  vendor: default
  # interval: 60000
  # schedule: "1/60 * * * * *"
  useINotify: true
  includeCrioExe: false
  # S3 access
  manageStoreSecret: true
  s3AccessKey : XXX
  s3Secret : XXX
  s3BucketName : XXX
  s3Region : XXX
  extraEnvVars: ""
serviceAccount:
  create: true
  name: "core-dump-admin"

clusterRole:
  name: "core-dump-event-reporter"

clusterRoleBinding:
  name: "core-dump-event-report"

# nodeSelector & affinity for the daemonset's pod assignment
# https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#running-pods-on-select-nodes
nodeSelector: {}
# eg
# gpu-enabled: true
affinity: {}

# Tolerations for the daemonset's pod assignment
# ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []
# eg
# - key: "key"
#   operator: "Equal"
#   value: "value"
#   effect: "NoSchedule"
